dist: trusty
language: php

branches:
  # Only test the master branch and SemVer tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: 'SCENARIO=symfony4 DEPENDENCIES=highest'
    - php: 7.1
      env: 'SCENARIO=symfony4'
    - php: 7.0.11
      env: 'DEPENDENCIES=highest'
    - php: 7.0.11
    - php: 5.6
    - php: 5.6
      env: 'DEPENDENCIES=lowest'
    - php: 5.5
      env: 'SCENARIO=symfony2 DEPENDENCIES=lowest'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - 'composer scenario "${SCENARIO}" "${DEPENDENCIES}"'

script:
  - composer test

after_success:
  - travis_retry php vendor/bin/coveralls -v

# Prior to a deploy, build a fresh robo.phar
before_deploy:
  - ./robo phar:build

# Deploy instructions set up via `travis setup releases` per
# https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key:
    secure: EdmB1nW5gj5nggYfmHv20enSgvRIAl1PIWV5GKmkxAJwuummh3UqdI7z0ecTGdw2IBgJx9lizNvqhcWjXbpNhE9VaaT1sHFCKv4Zust6sLb9bneK3oLRdJk2wemfrrZQpdH900zA0o7b3CHVth8UhkrCB4FXVDjUW13K061EXG8=
  file: robo.phar
  skip_cleanup: true
  on:
    tags: true
